### ISSUE TITLE
Support .flac/.ape format in the future?

### ISSUE THREAD

**Issue by vindevil** [XDGFX/ultrasonics#18] opened 2020-11-02 12:38 UTC
Plex failed importing playlist for most of my music files are stored in .flac or .ape format.

However, the online sync service [Soundiiz](https://soundiiz.com/) does transfer playlist into Plex successfully with the same music library.

So I think maybe there is a chance that Ultrasonics could recognize .flac/.ape files in the future? Thanks.

**Comment by vindevil** [comment] 2020-11-02 23:19
Today I found [another project](https://github.com/bassrock/spotify-plex-playlists) on Github can recognize .flac files and import Spotify playlist into Plex.

Hope this will benefit this project a bit.

**Comment by XDGFX** [comment] 2020-11-03 15:52
Thanks for the feedback! I have been very busy with uni so haven't had the chance to expand functionality recently.

I am planning on adding `.flac` support for 1.1.0. I have actually added it already in the [1.1.0 branch](https://github.com/XDGFX/ultrasonics/tree/1.1.0), however I haven't tested it at all yet so can't promise it works 😉

Not sure about `.ape`, it looks like the module I'm using, `mutagen`, [does support it](https://mutagen.readthedocs.io/en/latest/api/ape.html) so I'll look into it when I get some time.

**Comment by vindevil** [comment] 2020-11-04 07:34
Very glad to hear that. Currently I can deal with it by using the other project metioned above. Please keep focusing on your uni and I will come back later to check if I'm lucky enough.

**Comment by nisegami** [comment] 2021-09-04 20:19
Any progress on this issue? If testing is your concern I'd be down to try it out. Thanks!

**Comment by XDGFX** [comment] 2021-09-06 09:33
I've just updated the [1.1.0 branch](https://github.com/XDGFX/ultrasonics/tree/1.1.0) to include changes made on the master branch. #28 

If you're up for testing it with a few flac files to make sure it's working as intended that would be great!

Easiest way would likely be putting breakpoints at the `.flac` part of the plugin [here](https://github.com/XDGFX/ultrasonics/blob/88d8b8b2d67436aed23d4587ce55233aa8e0345a/ultrasonics/tools/local_tags.py#L119-L132)

If you could verify that it successfully reads all the fields and artists from a few different files I'll update the master branch!

**Comment by nisegami** [comment] 2021-09-06 10:50
So I actually ended up doing a fork and cherry-picking 184cc7db94492e3fc99616db3a3e34c7ee33375a into master then building a local Docker image. I believe my FLAC tracks are being picked up now, but it's still a mismatch on the total number of tracks on my main playlist (local: 1528, Plex: 1476) so let me do some more testing and get back to you.

**Comment by nisegami** [comment] 2021-09-08 01:08
Reporting back. The FLAC fix seems to work fine. The # of files loaded mismatch seems to be an unrelated issue (it affects both FLAC and MP3 files, don't have a ton of M4A but none of the few I do have are affected), I'm investigating that further but I will file another issue for that if necessary.

**Comment by XDGFX** [comment] 2021-09-13 10:12
Awesome thanks for the feedback! I'll close this issue as it seems .flac is working for the next release, and I don't have immediate plans to support .ape (although PRs are welcome!).

**Closed by XDGFX** 2021-09-13 10:12 UTC

**Comment by samplethief** [comment] 2022-08-26 18:48
Hey buddy is flac supported now?

It still says on the applet creation screen that "⚠️ Only .m3u extensions are supported for playlists, and .mp3, m4a extensions are supported for audio files. Unsupported files will be ignored."

But messages in this thread seem to indicate otherwise?
